on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Magnet URL'     
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: NPM Install
        run: npm install

      - name: Initial
        run: node src/get.js -i ${{ github.event.inputs.url }}

      - name: Check Directory
        run: ls

      - name: Check Directory SRC
        run: ls src/

      - name: Compile
        run: |
          echo "COMPILED"
      
      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@4.1.1
      #   with:
      #     branch: gh-pages # The branch the action should deploy to.
      #     folder: build # The folder the action should deploy.