on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Magnet URL'     
        required: true
        default: 'Magnet URL'
  
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "MAGNET: ${{ github.event.inputs.url }}"
