on:
  workflow_call:
    inputs:
      magnet:
        description: 'Magnet URL'
        default: 'Magnet URL'
        required: true
        type: string
  
jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.magnet }}
